apiVersion: apps/v1
kind: Deployment 
metadata: 
 name: my-djano-app
 labels:
   app: my-django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-django-app
  template:
    metadata: 
     labels:
      app: my-django-app
    spec:
     containers:
       - name: my-django-app
         image: prathiksha3/djan
         ports:
          - containerPort: 8000   
