apiVersion: v1
kind: Service
metadata:
  name: my-django-app
  labels:
    app: my-django-app
spec:
  type: NodePort
  selector:
    app: my-django-app
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 31236
      protocol: TCP
